name: 'Zola Deploy to Pages (with zola/next)'
description: 'Build and deploy a Zola site to GitHub Pages, using the latest features from zola/next'
author: 'Éric NICOLAS (ccjmne)'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ccjmne/zola-deploy-action:latest'
branding:
  icon: 'zap'
  color: 'green'
