name: Publish Image

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Resolve SHA of getzola:zola/next
        id: zola
        uses: actions/github-script@v8
        with:
          script: |
            const { data: { commit: { sha } } } = await github.rest.repos.getBranch({
              owner: 'getzola',
              repo: 'zola',
              branch: 'next'
            })
            const tag = `zola-next-${sha.substring(0,7)}`
            const found = await github.rest.repos.getReleaseByTag({ owner: context.repo.owner, repo: context.repo.repo, tag })
              .then(({ status }) => status === 200)
              .catch(({ status }) => status === 200)
            core.setOutput('sha', sha)
            core.setOutput('short', sha.substring(0,7))
            core.setOutput('tag', tag)
            core.setOutput('found', String(found))
            core.info(found ? `Release '${tag}' already exists` : `Create release for '${tag}'...`)

      - name: Login to GHCR
        if: steps.release_check.outputs.found == false
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        if: steps.release_check.outputs.found == false
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/zola-deploy-action:latest
            ghcr.io/${{ github.repository_owner }}/zola-deploy-action:${{ steps.zola.outputs.tag }}
          labels: |
            org.opencontainers.image.title=Zola Deploy Action
            org.opencontainers.image.version=${{ steps.zola.outputs.tag }}
            org.opencontainers.image.description=Built against upstream getzola/zola@${{ steps.zola.outputs.short }} (Image tag: ${{ steps.zola.outputs.tag }})
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Create release
        if: steps.release_check.outputs.found == false
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.repos.createRelease({
              repo:                   context.repo.repo,
              owner:                  context.repo.owner,
              tag_name:               '${{ steps.zola.outputs.tag }}',
              name:                   '${{ steps.zola.outputs.tag }}',
              generate_release_notes: false,
              body:                   `Built against getzola/zola@${{ steps.zola.outputs.short }}`
            })
