name: Publish Image

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Resolve SHA of getzola:zola/next
        id: zola
        uses: actions/github-script@v7
        with:
          script: |
            const {data} = await github.rest.repos.getBranch({
              owner: 'getzola',
              repo: 'zola',
              branch: 'next'
            });
            const sha = data.commit.sha;
            core.setOutput('sha', sha);
            core.setOutput('short', sha.substring(0,7));

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image for getzola:zola/next
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/zola-deploy-action:latest
            ghcr.io/${{ github.repository_owner }}/zola-deploy-action:next-${{ steps.zola.outputs.short }}
